language: haxe
haxe:
  - "3.4.2"
neko: "2.0.0"
hxml:
  - test.hxml
install:
  - git clone https://github.com/nightblade9/haxesharp
  - cd haxesharp
  - haxelib dev haxesharp .
  - a | haxelib install test.hxml
script:  
  - haxelib run munit test -coverage -result-exit-code