language: haxe
haxe:
  - "3.4.2"
neko: "2.1.0"
hxml:
  - test.hxml
install:
  - haxelib install flixel > /dev/null
  - haxelib install flixel-addons >/dev/null
  - haxelib install PathFinder >/dev/null
  - haxelib git helix https://github.com/nightblade9/helix
  - haxelib git haxesharp https://github.com/nightblade9/haxesharp
  - haxelib install munit > /dev/null
script:  
  - haxelib run munit test --coverage -result-exit-code