language: haxe
haxe:
  - "3.4.2"
neko: "2.0.0"
hxml:
  - test.hxml
install:
  - haxelib git haxesharp https://github.com/nightblade9/haxesharp
  - haxelib install munit
  - haxelib install flixel
script:  
  - haxelib run munit test -coverage -result-exit-code