language: haxe
haxe:
  - "3.4.2"
neko: "2.0.0"
hxml:
  - test.hxml
install:
  - haxelib git haxesharp https://github.com/nightblade9/haxesharp > /dev/null
  - cd nightblade9/haxesharp
  - haxelib dev haxesharp .
  
  - haxelib install test.hxml  
script:  
  - haxelib run munit test -coverage -result-exit-code