language: haxe
haxe:
  - "3.4.2"
neko: "2.0.0"
hxml:
  - test.hxml
install:
  - haxelib git haxesharp https://github.com/nightblade9/haxesharp > /dev/null
script:
  haxelib run munit test -coverage -result-exit-code